-- Crear la base de datos del Data Warehouse
CREATE DATABASE DataWarehouse;

-- Utilizar la base de datos del Data Warehouse
USE DataWarehouse;

-- Creación de la tabla VENTAS
CREATE TABLE VENTAS (
    DOCUMENTO NVARCHAR(255) PRIMARY KEY,
    TIPO_DOCUMENTO NVARCHAR(255),
	CANTIDAD_PRODUCTO INT,
	TOTAL_PRODUCTO_PESOS NUMERIC(18,4),
	TOTAL_PRODUCTO_DOLAR NUMERIC(27,4),
	PRECIO_UNITARIO_DOLAR NUMERIC(27,4),
	CODIGO_PRODUCTO NVARCHAR(255),
    ID_CLIENTE NVARCHAR(255),
    ID_VENDEDOR SMALLINT,
    SUCURSAL_ID SMALLINT,
	FECHA DATE
);

-- Creación de la tabla CLIENTES
CREATE TABLE CLIENTES (
    ID_CLIENTE NVARCHAR(255) PRIMARY KEY,
    FECHA_NACIMIENTO DATE,
	EDAD TINYINT,
    ESTADO_CIVIL NVARCHAR(255)
);

-- Creación de la tabla ARTICULO
CREATE TABLE ARTICULO (
    CODIGO_PRODUCTO NVARCHAR(255) PRIMARY KEY,
    NOMBRE NVARCHAR(255),
    FAMILIA NVARCHAR(255)
);

-- Creación de la tabla VENDEDORES
CREATE TABLE VENDEDORES (
    ID_VENDEDOR SMALLINT PRIMARY KEY,
    NOMBRE NVARCHAR(255),
    APELLIDO NVARCHAR(255),
    TIPO_CAPACITACION NVARCHAR(255),
	HORAS_CAPACITACION INT
);

-- Creación de la tabla SUCURSAL
CREATE TABLE SUCURSAL (
    SUCURSAL_ID SMALLINT PRIMARY KEY,
    NOMBRE_SUCURSAL NVARCHAR(255),
    COMUNA_ID SMALLINT,
);

-- Creación de la tabla COMUNA
CREATE TABLE GEOGRAFIA (
    COMUNA_ID SMALLINT PRIMARY KEY,
    COMUNA_NOMBRE NVARCHAR(255),
    PROVINCIA_NOMBRE NVARCHAR(255),
    REGION NVARCHAR(255)
);

-- Creación de la tabla TIEMPO
CREATE TABLE TIEMPO (
  FECHA DATE PRIMARY KEY,
  DIA TINYINT,
  MES TINYINT,
  ANIO SMALLINT,
  TRIMESTRE TINYINT,
  DIA_SEMANA TINYINT,
  NOMBRE_DIA VARCHAR(50)
);


-- Creación de las relaciones entre tablas
ALTER TABLE VENTAS ADD FOREIGN KEY (FECHA) REFERENCES TIEMPO (FECHA);
ALTER TABLE VENTAS ADD FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE);
ALTER TABLE VENTAS ADD FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDORES (ID_VENDEDOR);
ALTER TABLE VENTAS ADD FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSAL (SUCURSAL_ID);
ALTER TABLE VENTAS ADD FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES ARTICULO (CODIGO_PRODUCTO);

ALTER TABLE SUCURSAL ADD FOREIGN KEY (COMUNA_ID) REFERENCES GEOGRAFIA (COMUNA_ID);

